### ISSUE TITLE
Crash Alert low

### ISSUE THREAD

**Issue by MXASoundNDEv** [Yuri6037/TSCM_Starfall#2]
[SF - ERROR] SF:lanai/processor/systems/ai_decoder.txt:137: attempt to call global 'CheckAutoMode' (a nil value)
[starfall_processor [2081]] Server Error
SF:lanai/processor/systems/ai_decoder.txt:137: attempt to call global 'CheckAutoMode' (a nil value)
stack traceback:
	SF:lanai/processor/systems/ai_decoder.txt:137: in function 'OnChatMessage'
	SF:lanai/processor/systems/ai_utils.txt:22: in function 'ReadData'
	SF:lanai/processor/systems/protocol.txt:85: in function <SF:lanai/processor/systems/protocol.txt:61>

**Comment by Yuri6037** [comment]
Does this happen after the core is completely initialized (that means no more yellow ligh) or does this happen while the core is initializing ?

**Comment by Yuri6037** [comment]
#3

**Comment by MXASoundNDEv** [comment]
on initialiez is done completely

**Comment by Yuri6037** [comment]
Ok then I'll have a look asap.

**Comment by Yuri6037** [comment]
I checked it and I can't reproduce the crash when LanAI is completely initialized...
EDIT : Right the crash can be reproduced on any command when used before the core has fully initialized

**Comment by Yuri6037** [comment]
Should be fixed now, comment if it's not...

**Comment by Yuri6037** [comment]
#4
