### ISSUE TITLE
Crash Enable energy

### ISSUE THREAD

**Issue by MXASoundNDEv** [Yuri6037/TSCM_Starfall#3]
[SF - ERROR] SF:lanai/processor/systems/ai_decoder.txt:137: attempt to call global 'CheckAutoMode' (a nil value)
[starfall_processor [2196]] Server Error
SF:lanai/processor/systems/ai_decoder.txt:137: attempt to call global 'CheckAutoMode' (a nil value)
stack traceback:
	SF:lanai/processor/systems/ai_decoder.txt:137: in function 'OnChatMessage'
	SF:lanai/processor/systems/ai_utils.txt:22: in function 'ReadData'
	SF:lanai/processor/systems/protocol.txt:85: in function <SF:lanai/processor/systems/protocol.txt:61>

**Comment by Yuri6037** [comment]
Closing as this issue is happening in the same file at same line.
